docs: add link to EOL blog post and update guidance
angular/bower-material pull request #46
Opened 2022-02-17 19:33 UTC by Splaktar

- update copyright year
- add more context around AngularJS Material and Angular Material (based on review feedback)
- add link to Angular core package (based on review feedback)

Related to https://github.com/angular/bower-angular/pull/49

cc: @mgol @mgechev @gkalpak @aaronfrost

2022-02-22 03:34 UTC, mgechev commented on README.md
> +**[Support for legacy AngularJS ended on January 1st, 2022](https://goo.gle/angularjs-end-of-life).**
Can we have a sentence about Angular here?

2022-02-22 03:35 UTC, mgechev commented on README.md
> +This repository was used to publish the AngularJS Material v1.x library and localized installs
Can we have a sentence about Angular Material here?

2022-02-22 03:35 UTC, mgechev requested changes
Few suggestions

2022-02-23 19:56 UTC, Splaktar commented on README.md
> +This repository was used to publish the AngularJS Material v1.x library and localized installs
Added below.

2022-02-23 19:56 UTC, Splaktar commented on README.md
> +**[Support for legacy AngularJS ended on January 1st, 2022](https://goo.gle/angularjs-end-of-life).**
Added.

2022-02-24 00:27 UTC, mgechev approved these changes

2022-02-24 06:44 UTC, merged